added documentation for translation review
oppia/creator-documentation pull request #18
Opened 2021-03-06 08:18 UTC by shubhamkorde

This PR adds documentation for translation reviews.

2021-03-06 09:09 UTC, shubhamkorde commented
@audstav PTAL

2021-03-06 19:46 UTC, audstav commented on docs/index.rst
> +Learn the procedure to :ref:`review translations <reviewatranslation>`, :ref:`voiceover <reviewavoiceover>` and :ref:`questions <reviewaquestion>` in Oppia.
Please change 'voiceover' to 'voiceovers' here

2021-03-06 20:07 UTC, audstav commented
@shubhamkorde Thanks, this looks pretty good! I left a few minor comments for when you get a chance.

@DubeySandeep can you PTAL at this as well, I will leave it to you to approve and merge :)

2021-03-17 22:58 UTC, sagangwee requested changes
@shubhamkorde Thanks for the changes. Added some comments.

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/review.rst
> +Reviewing is critical in ensuring that the translations, questions and voiceovers submitted by the contributors are correct and error-free. In order to review questions, translations or voiceovers, a
Nit: For consistency, prefer North American English, i.e. "authorized" rather than "authorised".

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/review.rst
> +The review rights a user has are listed in the header of the contributor-dashboard under the My Contributions tab. Review rights for translations and voiceovers are language specific whereas that for
Grammar fixes and minor improvements:

```suggestion
The review rights of a user are listed in the header of the Contributor Dashboard under the **My Contributions** tab. Review rights for translations and voiceovers are language specific whereas those for questions are not. The languages in which you can review translations and voiceovers are also listed in the header.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/review.rst
> +Review Rights
```suggestion
Reviewing Lesson Contributions
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +Oppia's lessons are translated to multiple languages to ensure a wide range of students across the world could learn in their own language. After translations are submitted, they are sent for review.
```suggestion
Oppia's lessons are translated to multiple languages to ensure a wide range of students across the world can learn in their own language. After translations are submitted, they are sent for review. As a reviewer, you can review all the translations in the language for which you have review rights.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +2. Select the translation you want to review buy clicking on the |reviewbtn| of that particular translation. A translation review modal will open up as shown in the figure.
```suggestion
2. Select the translation you want to review buy clicking on the |reviewbtn| button of that particular translation. A translation review modal will open up as shown in the figure.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +5. If the translation is correct, click on |acceptandreviewnextbtn| button approve it and review the next translation. Adding a review message is not mandatory for while accepting a translation.
```suggestion
5. If the translation is correct, click on the |acceptandreviewnextbtn| button to approve it and review the next translation. Adding a review message is not mandatory when accepting a translation.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +3. The left side text-box contains the original text in English and the right side text-box contains the translated text. Check if the translation is gramatically correct and conveys the same meaning
```suggestion
3. The left side text box contains the original text in English and the right side text box contains the translated text. Check if the translation is gramatically correct and conveys the same meaning as the original text. Please follow :ref:`the guidelines <reviewguidelines>`.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +6. If the translation is not correct, type a review message in the text-box with the label 'Review message' explaining the reason for rejection, possible improvements and suggestions. This message wo
```suggestion
6. If the translation is not correct, type a review message in the text box with the label 'Review message' explaining the reason for rejection and any possible improvements and suggestions. This message would be visible to the translator. Note that you cannot reject a translation without a review message.  Click on the |rejectandreviewnextbtn| button to continue reviewing other translations.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +7. Continue the same procedure till you have completed reviewing all the translations.
```suggestion
7. Continue the same procedure until you have completed reviewing all the translations.
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> +To ensure that translations convey the same meaning with same persuasiveness and simplicity as the original text, please keep these principles in mind:
Not sure if "persuasiveness" makes sense here?

```suggestion
To ensure that translations convey the same meaning with the same persuasiveness and simplicity as the original text, please keep these principles in mind:
```

2021-03-17 22:58 UTC, sagangwee commented on docs/reviewers/translations.rst
> + * Ensure that the the voice and meaning of the original text is preserved. It doesn't mean you have to accept only literal translations. If the language is natural and understandable that stays clos
```suggestion
 * Ensure that the the voice and meaning of the original text is preserved. It doesn't mean you have to accept only literal translations. If the language is natural, understandable, and stays close to the source, the translation is worth accepting.
```

2021-03-18 02:55 UTC, shubhamkorde commented on docs/reviewers/review.rst
> +Reviewing is critical in ensuring that the translations, questions and voiceovers submitted by the contributors are correct and error-free. In order to review questions, translations or voiceovers, a
Done!

2021-03-18 02:59 UTC, shubhamkorde commented on docs/reviewers/review.rst
> +The review rights a user has are listed in the header of the contributor-dashboard under the My Contributions tab. Review rights for translations and voiceovers are language specific whereas that for
Done!

2021-03-18 03:05 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +5. If the translation is correct, click on |acceptandreviewnextbtn| button approve it and review the next translation. Adding a review message is not mandatory for while accepting a translation.
Done.

2021-03-18 03:06 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +2. Select the translation you want to review buy clicking on the |reviewbtn| of that particular translation. A translation review modal will open up as shown in the figure.
Done.

2021-03-18 03:06 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +Oppia's lessons are translated to multiple languages to ensure a wide range of students across the world could learn in their own language. After translations are submitted, they are sent for review.
Done.

2021-03-18 03:07 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +3. The left side text-box contains the original text in English and the right side text-box contains the translated text. Check if the translation is gramatically correct and conveys the same meaning
Done.

2021-03-18 03:09 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +6. If the translation is not correct, type a review message in the text-box with the label 'Review message' explaining the reason for rejection, possible improvements and suggestions. This message wo
Done.

2021-03-18 03:12 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> +To ensure that translations convey the same meaning with same persuasiveness and simplicity as the original text, please keep these principles in mind:
should I replace 'persuasiveness' with 'effectiveness'?

2021-03-18 03:13 UTC, shubhamkorde commented on docs/reviewers/translations.rst
> + * Ensure that the the voice and meaning of the original text is preserved. It doesn't mean you have to accept only literal translations. If the language is natural and understandable that stays clos
Done.

2021-03-23 19:07 UTC, sagangwee approved these changes
@shubhamkorde Thanks. LGTM, just one last change.

2021-03-23 19:07 UTC, sagangwee commented on docs/reviewers/translations.rst
> +To ensure that translations convey the same meaning with the same persuasiveness and simplicity as the original text, please keep these principles in mind:
```suggestion
To ensure that translations convey the same meaning as the original text, please keep these principles in mind:
```

Let's just remove it.

2021-03-23 19:08 UTC, sagangwee approved these changes

2021-03-24 20:43 UTC, sagangwee commented
@seanlip Can you merge this, or give me write access to this repo? Thanks.

2021-03-24 22:40 UTC, seanlip commented
Done! @sagangwee gave you write access.

2021-03-24 23:07 UTC, merged